/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: "class",
    content: [
        "./app/**/*.{js,ts,jsx,tsx,mdx}",
        "./pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./components/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            colors: {
                "on-surface-variant": "#52443a",
                "tertiary-fixed": "#d0ed94",
                "on-tertiary": "#ffffff",
                "surface-container-low": "#fff1ea",
                "tertiary-fixed-dim": "#b4d17b",
                "tertiary-container": "#637c30",
                "inverse-surface": "#372f2a",
                "on-secondary-container": "#7c3066",
                "surface-container": "#faebe4",
                "surface-container-lowest": "#ffffff",
                "surface-container-highest": "#eee0d8",
                "outline-variant": "#d7c3b6",
                background: "#fff8f5",
                "surface-container-high": "#f4e5de",
                "surface-variant": "#eee0d8",
                secondary: "#914278",
                "surface-tint": "#8a501f",
                error: "#ba1a1a",
                "secondary-container": "#ffa0dc",
                "inverse-on-surface": "#fdeee6",
                "on-error-container": "#93000a",
                "on-tertiary-fixed": "#141f00",
                "on-primary-fixed-variant": "#6d3908",
                "on-tertiary-container": "#f6ffdc",
                "surface-dim": "#e5d7d0",
                "secondary-fixed": "#ffd8ed",
                "on-secondary-fixed": "#3b002e",
                "primary-fixed-dim": "#ffb781",
                primary: "#864d1c",
                "on-surface": "#211a16",
                "on-primary-fixed": "#2f1400",
                "on-secondary-fixed-variant": "#742a5f",
                outline: "#857469",
                "surface-bright": "#fff8f5",
                "primary-fixed": "#ffdcc4",
                "on-primary-container": "#fffaf9",
                "inverse-primary": "#ffb781",
                "on-error": "#ffffff",
                tertiary: "#4b631a",
                "error-container": "#ffdad6",
                "on-background": "#211a16",
                "secondary-fixed-dim": "#ffade0",
                "on-secondary": "#ffffff",
                "primary-container": "#a36532",
                "on-primary": "#ffffff",
                "on-tertiary-fixed-variant": "#384e04",
                surface: "#fff8f5"
            },
            borderRadius: {
                DEFAULT: "1rem",
                lg: "2rem",
                xl: "3rem",
                full: "9999px"
            },
            spacing: {
                gutter: "24px",
                unit: "8",
                "container-max": "1280px",
                "section-gap": "80px",
                "margin-mobile": "20px"
            },
            fontFamily: {
                "display-lg": ["Lora"],
                "headline-md": ["Lora"],
                "label-md": ["DM Sans"],
                "body-md": ["DM Sans"],
                "headline-lg": ["Lora"],
                headline: ["Lora"],
                display: ["Lora"],
                body: ["Dm Sans"],
                label: ["Dm Sans"],
                "display-lg-mobile": ["Lora"],
                "body-lg": ["DM Sans"],
                "headline-lg-mobile": ["Lora"]
            },
            fontSize: {
                "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "700" }],
                "display-lg-mobile": ["40px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "700" }],
                "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
                "display-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.01em", fontWeight: "700" }],
                "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
                "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
                "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
                "headline-lg-mobile": ["28px", { lineHeight: "34px", fontWeight: "600" }]
            }
        },
    },
    plugins: [],
};